---
- name: install required packages
  package:
    name:
      - cifs-utils
    state: present
  become: true

- name: Create mounting points
  file:
    path: "/media/diskstation/{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true
  with_items: "{{ folders }}"

- name: Set credentials
  template:
    src: credentials.j2
    dest: "/root//.diskstation_credentials"
    mode: "0600"
    owner: "root"
  become: true

- name: Create fstab entries
  mount:
    src: "//{{ server }}/{{ item }}/"
    path: "/media/diskstation/{{ item }}"
    fstype: "cifs"
    opts: "iocharset=utf8,vers=3.0,credentials=/home/{{ ansible_user_id }}/.diskstation_credentials,user,rw,nounix,uid=1000,gid=1000"
    state: present
  become: true
  with_items: "{{ folders }}"
