---
- name: Converge
  hosts: all
  tasks:
    - name: "Include diskstation"
      include_role:
        name: "diskstation-role"
      vars:
        username: test
        password: test
        server: testserver
