---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/pycontribs/fedora
    pre_build_image: true
lint:
  name: ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
