---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    server: testserver
    paths:
      - "git"
      - "home"
      - "photo"

  tasks:
    - name: Get installed packages
      package_facts:
        manager: "auto"

    - name: Check if cifs is installed
      assert:
        that: "'cifs-utils' in ansible_facts.packages"

    - name: Get diskstation mounting points
      stat:
        path: "/media/diskstation/{{ item }}"
      register: mountpoints
      with_items: "{{ paths }}"

    - name: Check if mounting point exists
      assert:
        that: "{{ item.stat.exists  }}"
      with_items: "{{ mountpoints.results }}"

    - name: Get the credentials file
      stat:
        path: "/root/.diskstation_credentials"
      register: credentialsfile

    - name: Check if credentials file exists
      assert:
        that:
          - "{{ credentialsfile.stat.exists }}"
          - credentialsfile.stat.mode == "0600"
          - credentialsfile.stat.uid == 0

    - name: Get the content of the /etc/fstab
      shell: "cat /etc/fstab"
      register: fstab

    - name: Check if the diskstation mounts are inside
      assert:
        that: "'//{{ server }}/{{ item }}/ /media/diskstation/{{ item }} cifs iocharset=utf8,vers=3.0,credentials=/root/.diskstation_credentials,nounix,uid=1000,gid=1000 0 0' in fstab.stdout_lines"
      with_items: "{{ paths }}"
